# Generated by Django 5.0 on 2023-12-23 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('details', models.CharField(default='No description', max_length=500)),
                ('genre', models.CharField(default='Not defined', max_length=50)),
                ('language', models.CharField(default='Not defined', max_length=20)),
                ('cover_image', models.ImageField(default='Not defined', upload_to='book_covers/')),
                ('pages', models.PositiveIntegerField(default=1000)),
                ('is_available', models.CharField(choices=[('Wanted', 'Wanted'), ('Available', 'Available')], max_length=20)),
                ('upload_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.PositiveBigIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
