version: '3'
services:
  app:
    build: src
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cloud
      MYSQL_DATABASE: cloud
      MYSQL_USER: cloud
      MYSQL_PASSWORD: cloud


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
