version: '3'
services:
  app:
    build:
      context: src
      args:
        - IMAGE_TAG=latest
    image: ashabir/book_cycle_django-app:${IMAGE_TAG}
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
