name: Build and Push "wr" Image

on:
  push:
    branches:
      - wr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Compose Service
        run: docker-compose build app

      - name: Tag Docker Compose image
        run: docker tag $(docker-compose images -q app) ashabir/book_cycle_django-app:wr
        working-directory: ./project-root

      - name: Push Docker Compose Image
        run: docker push ashabir/book_cycle_django-app:wr