name: Build and Push "workflowtest" Image

on:
  push:
    branches:
      - wr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build and push Docker Compose
        run: docker compose build
        env:
          DOCKER_BUILDKIT: 1

      - name: Tag Docker Compose image
        run: docker tag your_compose_service_name:latest ${{ secrets.DOCKERHUB_USERNAME }}/book_cycle_django-app:wr

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Compose
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/book_cycle_django-app:wr
