name: Build and Push Image in workflow test

on:
  push:
    branches:
      - wr

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_TAG: wr

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: |
          docker-compose --version
          docker-compose version
          docker version

      - name: Build and Push Docker Compose Image
        run: |
          docker-compose -f docker-compose.yml build app --build-arg IMAGE_TAG=${DOCKER_IMAGE_TAG}
          docker-compose -f docker-compose.yml push app

