name: Build and Push "workflowtest" Image

on:
  push:
    branches:
      - wr

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Compose Service
        run: docker-compose build app
        working-directory: .

      - name: Tag Docker Compose Service
        run: docker tag app ashabir/book_cycle_django-app:wr
        working-directory: .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Push Docker Compose Image
        run: docker push ashabir/book_cycle_django-app:wr
        working-directory: .
