name: Build and Push "workflow test" Image

on:
  push:
    branches:
      - wr
      - f_cc2

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps: 
      - 
        name: Checkout 
        uses: actions/checkout@v2 
      - 
        name: Set up QEMU 
        uses: docker/setup-qemu-action@v1 
      - 
        name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v1 
      - 
        name: Login to Docker Hub 
        uses: docker/login-action@v1 
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with: 
          context: "{{defaultContext}}:src"
          file: Dockerfile
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/book_cycle_django-app:wr
